apiVersion: v1
kind: Pod
metadata:
  name: flaskpod
  labels: 
    app: flaskpod
spec:
  containers:
  - name: flask
    image: hyunowk/flaskapp:latest
    ports:
    - containerPort: 5000
    
  imagePullSecrets:
  - name: myregistrykey