apiVersion: v1

kind: Pod

metadata:

  name: flaskapp-pod
  labels: 
    app: flaskpod

spec:

  containers:

  - name: flaskapp

    image: hyunowk/flaskapp:latest

    ports:

    - containerPort: 5000
  imagePullSecrets:
  - name: myregistrykey